repos:
-   repo: local
    hooks:
    -   id: snyk-iac
        name: snyk-iac
        description: Audit IAC with Snyk.
        entry: snyk-iac.sh
        language: script
        pass_filenames: false
        files: (\.tf|\.tfvars)$
        stages: [commit]

