repos:
-   repo: local
    hooks:
    -   id: snyk-iac
        name: snyk-iac
        description: Test IAC with Snyk.
        entry: snyk-iac.sh
        language: script
        files: (\.tf|\.tfvars)$
        stages: [push]

    -   id: snyk-test
        name: snyk-test
        description: Audit javascript library with Snyk.
        entry: snyk-test.sh
        language: script