repos:
-   repo: local
    hooks:
    -   id: snyk-audit
        name: snyk-audit
        description: Audit javascript library with Snyk.
        entry: snyk-test.sh
        language: script
        stages: [pre-commit]

    -   id: snyk-iac
        name: snyk-iac
        description: Audit IAC with Snyk.
        entry: snyk-iac.sh
        language: script

