repos:
-   repo: local
    hooks:
    -   id: snyk-test
        name: snyk-test
        description: Audit IAC with Snyk.
        entry: snyk-test.sh
        language: script
        pass_filenames: false
        files: (\.tf|\.tfvars)$
        stages: [commit]

